### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by KonstantinGolub** [sergeymirasov/megafon-game#1]
приветствую. можешь объяснить для чайника решение 2-й задачи мегафона? Что за а и б по 1 и почему с так вычисляется?

**Comment by Andrey-Matanov** [comment]
> приветствую. можешь объяснить для чайника решение 2-й задачи мегафона? Что за а и б по 1 и почему с так вычисляется?

а и б это по сути значения предыдущих элементов числовой последовательности. Каждый элемент этой числовой последовательности можно представить как сумму двух предыдущих, а нулевое и первое значение заданы фиксированно: a(0) = 0, a(1) = 1, a(n) = a(n - 1) + a(n - 2). Загугли, что такое числа Фибоначчи, если хочешь очень подробно рассмотреть этот вопрос.

**Comment by Andrey-Matanov** [comment]
Было бы неплохо, если бы мне тоже кто-то помог с 4 задачей, я либо глупый, либо задачу составили максимально коряво, вообще не могу разобраться.
Вот условие:

У вас есть шифр, чтобы подключить напрямую и отключить всю систему пятнистого черепа. Для этого нужно сделать все правильно, вот задача:

Перед вами в ряд расположены рубильники switches. Вы можете переключать каждый не более switches[i] раз. 
Но если вы переключаете 2 рубильника подряд, у системы срабатывает защитный механизм и вы проваливаете задачу. Определите, какое максимальное количество переключений вы сможете сделать.

На входе: массив неотрицательных целых чисел switches, switches.length >= 0
На выходе: целое число - максимальное количество переключений  

Пример:  

switches =  [2,7,9,3,1]
changeTheSwitches(switches) => 12
переключение первого рубильника (2 раза), третьего (9 раз) и пятого (1 раз) - максимальное значение 12

**Comment by KonstantinGolub** [comment]
Мне бы 3-ю до ума довести. 5/6 проходит, что еще одно за условие такое, надо подумать. Ну тут у меня кривое, но свое решение, через разбитие входных данных через split, дальше перевод времени диапазонов в минуты и сравнение целевого времени и диапазонов. Лютый треш конечно, но по другому пока скиллов не хватает...

**Comment by KonstantinGolub** [comment]
> 
> 
> > приветствую. можешь объяснить для чайника решение 2-й задачи мегафона? Что за а и б по 1 и почему с так вычисляется?
> 
> а и б это по сути значения предыдущих элементов числовой последовательности. Каждый элемент этой числовой последовательности можно представить как сумму двух предыдущих, а нулевое и первое значение заданы фиксированно: a(0) = 0, a(1) = 1, a(n) = a(n - 1) + a(n - 2). Загугли, что такое числа Фибоначчи, если хочешь очень подробно рассмотреть этот вопрос.

Я так понял надо было увидеть в том, что было дано, что это Фибонначи и потом уже от этого плясать. Не сообразил.

**Comment by KonstantinGolub** [comment]
по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...

**Comment by Andrey-Matanov** [comment]
> по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...

Расскажи плз, как ты понимаешь условие это задачи. Без всякого кода, чтобы понимать, что нужно сделать

**Comment by KonstantinGolub** [comment]
по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...

> 
> 
> > по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...
> 
> Расскажи плз, как ты понимаешь условие это задачи. Без всякого кода, чтобы понимать, что нужно сделать

А ты посмотри как они получили 12, какие элементы взяли и по условию элементы не могут быть подряд. Я сделал подсчет суммы четных и подсчёт суммы нечетных и вывод большего из них. вот 7/8 ок, а что еще может быть не могу сообразить, почему последний тест не проходит. если разберешься, подскажи хоть?

**Comment by Andrey-Matanov** [comment]
> по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...
> 
> > > по 4 задаче, первая же пришедшая мысль дала 7/8 по тесту, теперь понять чего не хватает...
> > 
> > 
> > Расскажи плз, как ты понимаешь условие это задачи. Без всякого кода, чтобы понимать, что нужно сделать
> 
> А ты посмотри как они получили 12, какие элементы взяли и по условию элементы не могут быть подряд. Я сделал подсчет суммы четных и подсчёт суммы нечетных и вывод большего из них. вот 7/8 ок, а что еще может быть не могу сообразить, почему последний тест не проходит. если разберешься, подскажи хоть?

Спасибо за подсказку. В общем, нужно рассматривать суммы не четных/нечетных чисел, а рассматривать подсуммы с условием, что новое слагаемое суммы брать через каждое одно/два числа, все суммы не нужно рассматривать. Рассмотрим например этот массив: [3, 2, 2, 3]. Здесь максимальное число переключений равно 3+3.
Я решил рекурсией, цикл тут лучше не использовать.

**Comment by KonstantinGolub** [comment]
Благодарю за подсказку.
